### PR TITLE
self explanatory minor changes for forwards compliance to python3

### PR DESCRIPTION
**Pull request by russelljjarvis**
Same as previous pull request, except noticed another py2/3 compatibility breach:
Idioms like this:
if "BUILD SUCCESS" in info  
Must explicitly be cast to string. I don't really understand why but it seems to work.
if "BUILD SUCCESS" in str(info)

### CODE REVIEW

**Comment by pgleeson** [comment]
Thanks for looking into this @russelljjarvis. Python 3 for building jnml has not really been well tested until now, though pyNeuroML works fine on P3. Offline for the next week or two but will merge this then.

**Comment by rgerkin** [comment]
@pgleeson Is this ready to merge?

**Comment by pgleeson** [comment]
Thanks @russelljjarvis, looks fine, but can you open a PR to the development branch for this? You (and @rgerkin) should ideally just be using the development branches of jNeuroML etc. as the jar generated from these is what's used inside pyNeuroML.

**Comment by rgerkin** [comment]
@pgleeson Thanks, we will reopen this to the dev branch. @russelljjarvis

**Comment by pgleeson** [comment]
Ok, will wait for that...

**Comment by pgleeson** [comment]
@russelljjarvis @rgerkin these changes have been merged into the development branch now.

**Pull request closed without merging**
